import { Zap, TrendingUp, DollarSign, FileText, ArrowRight } from "lucide-react"

export default function AIRecommendation() {
    const recommendation = [
        {
            title: "Save 4 Hours Per Week",
            description: "Automate repetative workflow tasks using AI automation",
            icon: Zap,
            color: "bg-indigo-50 text-indigo-600",
        },
        {
            title: "Increase Engagement",
            description: "Your content capaign is performing 23% better than last week",
            icon: TrendingUp,
            color: "bg-green-50 text-green-600",
        },
        {
            title: "Reduce AI Costs",
            description: "Unused credits were detected.Optimize resource usage",
            icon: DollarSign,
            color: "bg-amber-50 text-amber-600",
        },
        {
            title: "Review Pending Reports",
            description: "3 reports are waiting for approval from your team.",
            icon: FileText,
            color: "bg-blue-50 text-blue-500"
        }
    ]
    return (
        <section className="rounded-4xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="mb-6">
                <h2 className="text-xl font-semibold text-slate-900">AI Recommendation</h2>
                <p className="text-sm text-slate-500">Personalized suggestions generated by AI</p>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
                {recommendation.map((item)=>{
                    const Icon = item.icon
                    return(
                        <div key={item.title} className="group rounded-3xl border border-slate-100 p-5 transition-all duration-300 hover:-translate-y-1 hover:border-indigo-100 hover:shadow-md">
                            <div className={`mb-4 flex h-12 w-12 items-center justify-center rounded-2xl ${item.color}`}>
                                <Icon size={22} />
                            </div>

                            <h3 className="font-semibold text-slate-900">{item.title}</h3>
                            <p className="text-sm mt-2 leading-relaxed text-slate-500">
                                {item.description}
                            </p>

                            <div className="mt-4 flex items-center gap-2 text-sm font-medium text-slate-600">
                                View Recommendation
                                <ArrowRight size={16} className="transition-transform duration-300 group-hover:translate-1"/>
                            </div>
                        </div>
                    )
                })}
            </div>

        </section>
    )
}
